<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment+, (acronym,expanded-acronym)? , (icon? | generic-icon? | glob | magic | treemagic | root-XML | alias | sub-class-of)*)>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!-- a comment describing a document with the respective MIME type. Example: "WMV video" -->
  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!-- a comment describing the respective unexpanded MIME type acronym. Example: "WMV" -->
  <!ELEMENT acronym (#PCDATA)>
  <!ATTLIST acronym xml:lang CDATA #IMPLIED>

  <!-- a comment describing the respective expanded MIME type acronym. Example: "Windows Media Video" -->
  <!ELEMENT expanded-acronym (#PCDATA)>
  <!ATTLIST expanded-acronym xml:lang CDATA #IMPLIED>

  <!ELEMENT icon EMPTY>
  <!ATTLIST icon name CDATA #REQUIRED>

  <!-- a generic icon name as per the Icon Naming Specification, only required if computing
  it from the mime-type would not work, See "generic-icon" in the Shared Mime Specification -->
  <!ELEMENT generic-icon EMPTY>
  <!ATTLIST generic-icon name (application-x-executable|audio-x-generic|folder|font-x-generic|image-x-generic|package-x-generic|text-html|text-x-generic|text-x-generic-template|text-x-script|video-x-generic|x-office-address-book|x-office-calendar|x-office-document|x-office-presentation|x-office-spreadsheet) #REQUIRED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>
  <!ATTLIST glob weight CDATA "50">
  <!ATTLIST glob case-sensitive CDATA #IMPLIED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA "50">

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT treemagic (treematch)+>
  <!ATTLIST treemagic priority CDATA "50">

  <!ELEMENT treematch (treematch)*>
  <!ATTLIST treematch path CDATA #REQUIRED>
  <!ATTLIST treematch type (file|directory|link) #IMPLIED>
  <!ATTLIST treematch match-case (true|false) #IMPLIED>
  <!ATTLIST treematch executable (true|false) #IMPLIED>
  <!ATTLIST treematch non-empty (true|false) #IMPLIED>
  <!ATTLIST treematch mimetype CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML namespaceURI CDATA #REQUIRED>
  <!ATTLIST root-XML localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-atari-2600-rom">
    <comment>Atari 2600</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a26"/>
  </mime-type>
  <mime-type type="application/x-atari-7800-rom">
    <comment>Atari 7800</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a78"/>
    <magic>
      <match value="ATARI7800" type="string" offset="1"/>
    </magic>
  </mime-type>
  <mime-type type="application/andrew-inset">
    <comment>ATK inset</comment><!-- bug 404713 - next line is double height and either overpaint the next one or is overpainted -->
    <comment xml:lang="ar">شكل ATK</comment>
    <comment xml:lang="be@latin">Ustaŭka ATK</comment>
    <comment xml:lang="bg">Сбор — ATK</comment>
    <comment xml:lang="ca">ATK inset</comment>
    <comment xml:lang="cs">vložka ATK</comment>
    <comment xml:lang="da">ATK-indsættelse</comment>
    <comment xml:lang="de">ATK-Inset</comment>
    <comment xml:lang="el">Ένθετο ATK</comment>
    <comment xml:lang="en_GB">ATK inset</comment>
    <comment xml:lang="es">inserción ATK</comment>
    <comment xml:lang="eu">ATK sartzapena</comment>
    <comment xml:lang="fi">ATK-osio</comment>
    <comment xml:lang="fo">ATK innskot</comment>
    <comment xml:lang="fr">encart ATK</comment>
    <comment xml:lang="ga">intlis ATK</comment>
    <comment xml:lang="gl">conxunto ATK</comment>
    <comment xml:lang="he">תוספת ATK</comment>
    <comment xml:lang="hr">ATK umetak</comment>
    <comment xml:lang="hu">ATK betét</comment>
    <comment xml:lang="ia">Folio intercalari ATK</comment>
    <comment xml:lang="id">Inset ATK</comment>
    <comment xml:lang="it">Inset ATK</comment>
    <comment xml:lang="ja">ATK インセット</comment>
    <comment xml:lang="kk">ATK беті</comment>
    <comment xml:lang="ko">ATK inset</comment>
    <comment xml:lang="lt">ATK inset</comment>
    <comment xml:lang="lv">ATK ielaidums</comment>
    <comment xml:lang="nb">ATK-innsats</comment>
    <comment xml:lang="nl">ATK-invoegsel</comment>
    <comment xml:lang="nn">ATK-innskot</comment>
    <comment xml:lang="oc">encart ATK</comment>
    <comment xml:lang="pl">Wstawka ATK</comment>
    <comment xml:lang="pt">Suplemento ATK</comment>
    <comment xml:lang="pt_BR">Conjunto de entrada do ATK</comment>
    <comment xml:lang="ro">Inset ATK</comment>
    <comment xml:lang="ru">вкладка ATK</comment>
    <comment xml:lang="sk">Vložka ATK</comment>
    <comment xml:lang="sl">Vložka ATK</comment>
    <comment xml:lang="sq">Inset ATK</comment>
    <comment xml:lang="sr">АТК уметак</comment>
    <comment xml:lang="sv">ATK-inlägg</comment>
    <comment xml:lang="tr">ATK iç metni</comment>
    <comment xml:lang="uk">вкладка ATK</comment>
    <comment xml:lang="vi">Bộ dát ATK</comment>
    <comment xml:lang="zh_CN">ATK 嵌入对象</comment>
    <comment xml:lang="zh_TW">ATK 內嵌</comment>
    <acronym>ATK</acronym>
    <expanded-acronym>Andrew Toolkit</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/epub+zip">
    <comment>electronic book document</comment><!-- bug 404713 - next line is double height and either overpaint the next one or is overpainted -->
    <comment xml:lang="ar">مستند كتاب إلكتروني</comment>
    <comment xml:lang="be@latin">elektronnaja kniha</comment>
    <comment xml:lang="bg">Документ — електронна книга</comment>
    <comment xml:lang="ca">document de llibre electrònic</comment>
    <comment xml:lang="cs">dokument elektronické knihy</comment>
    <comment xml:lang="da">elektronisk bogdokument</comment>
    <comment xml:lang="de">Elektronisches Buch</comment>
    <comment xml:lang="el">Έγγραφο ηλεκτρονικού βιβλίου</comment>
    <comment xml:lang="en_GB">electronic book document</comment>
    <comment xml:lang="es">documento de libro electrónico</comment>
    <comment xml:lang="eu">liburu elektronikoaren dokumentua</comment>
    <comment xml:lang="fi">elektroninen kirja</comment>
    <comment xml:lang="fo">elektroniskbóka skjal</comment>
    <comment xml:lang="fr">document livre électronique</comment>
    <comment xml:lang="ga">leabhar leictreonach</comment>
    <comment xml:lang="gl">documento de libro electrónico</comment>
    <comment xml:lang="he">מסמך מסוג ספר אלקטרוני</comment>
    <comment xml:lang="hr">dokument elektroničke knjige</comment>
    <comment xml:lang="hu">elektronikus könyvdokumentum</comment>
    <comment xml:lang="ia">Documento de libro electronic</comment>
    <comment xml:lang="id">dokumen buku elektronik</comment>
    <comment xml:lang="it">Documento libro elettronico</comment>
    <comment xml:lang="ja">電子ブックドキュメント</comment>
    <comment xml:lang="kk">электронды кітабы</comment>
    <comment xml:lang="ko">전자책 문서</comment>
    <comment xml:lang="lt">elektroninės knygos dokumentas</comment>
    <comment xml:lang="lv">elektroniskās grāmatas dokuments</comment>
    <comment xml:lang="nl">elektronisch boek</comment>
    <comment xml:lang="nn">elektronisk bok-dokument</comment>
    <comment xml:lang="oc">document libre electronic</comment>
    <comment xml:lang="pl">Dokument książki elektronicznej</comment>
    <comment xml:lang="pt">documento de livro eletrónico</comment>
    <comment xml:lang="pt_BR">Documento de livro eletrônico</comment>
    <comment xml:lang="ro">document carte electronică</comment>
    <comment xml:lang="ru">электронная книга</comment>
    <comment xml:lang="sk">Dokument elektronickej knihy</comment>
    <comment xml:lang="sl">dokument elektronske knjige</comment>
    <comment xml:lang="sq">Dokument libri elektronik</comment>
    <comment xml:lang="sr">документ електронске књиге</comment>
    <comment xml:lang="sv">elektroniskt bokdokument</comment>
    <comment xml:lang="tr">elektronik kitap belgesi</comment>
    <comment xml:lang="uk">документ електронної книги</comment>
    <comment xml:lang="vi">tài liệu cuốn sách điện tử</comment>
    <comment xml:lang="zh_CN">电子书文档</comment>
    <comment xml:lang="zh_TW">電子書文件</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic priority="70">
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/epub+zip" type="string" offset="38"/>
          <match value="application/epub+zip" type="string" offset="43"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.epub"/>
  </mime-type>
</mime-info>
